### ISSUE TITLE
add information about photo quality to the reply when someone sends in a photo

### ISSUE THREAD

**Issue by bumi** [bumi/kuvakehys#10]
quite some photos that we receive have bad quality which is a problem for printing. 
We should notify the sender about this issue (and maybe later allow him to delete the picture)

**Comment by puneetbharill** [comment]
150DPI 900x600pixels is a good size for 10x15cm prints and 300DPI and 1800x1200 is ideal. This info is based on the chat with the guys at pwinty.

**Comment by bumi** [comment]
done in in: fd9420fcfbffcd6adf441410c4f8351fcc9d2c4c 
text needs to be better

**Comment by bumi** [comment]
@puneetbharill text that is sent to the user after the photo import is here: https://github.com/bumi/kuvakehys/blob/master/app/views/user_mailer/email_processed.text.erb
