### ISSUE TITLE
fixed delivery date instead of amount based limits

### ISSUE THREAD

**Issue by bumi** [bumi/kuvakehys#11]
I was wondering where else this app might be useful and thought about vacations or other events -  with a group (== 2 or more people).
The important thing is the "surprise" aspect of it: everyone sends in photos independently and after the event all the photos get printed and delivered. 

for that we would not need to define an amount limit but an end/delivery date.

**Comment by puneetbharill** [comment]
I like the idea of a surprise but in general the two three people I talked to always said that they would like to see what is being printed. Maybe this can be set as an option in the future if people want to go through what is being printed in an album.

**Comment by bumi** [comment]
do you know why they want to see it? I men they  are the ones who have sent
in the pictures...

On Monday, October 19, 2015, puneetbharill <notifications@github.com> wrote:

> I like the idea of a surprise but in general the two three people I talked
> to always said that they would like to see what is being printed. Maybe
> this can be set as an option in the future if people want to go through
> what is being printed in an album.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bumi/kuvakehys/issues/11#issuecomment-149190503>.
>


-- 
Michael Bumann

F       +49 (0) 176 22747893
E       hello@michaelbumann.com
T       twitter.com/bumi

**Comment by puneetbharill** [comment]
No, they want to see what is everyone sending in their group. Reasons could be the old habit of looking at every picture before deciding that they want to print it. I think realising that it is cheap and quick could take care of these issues that is why for me the surprise idea is very good and should stay.
