### ISSUE TITLE
setup exception tracking

### ISSUE THREAD

**Issue by bumi** [bumi/kuvakehys#12]
I mean our app has no bugs, but you know just in case :) 
What is a decent, cheap service to do that these days?

**Comment by kangguru** [comment]
maybe „rollbar“?

https://rollbar.com/pricing/

**Comment by bumi** [comment]
oh nice they have a free plan and 5000 events should be enough. :) 
thanks.

**Comment by kangguru** [comment]
\o/ i was also looking at getsentry but no free account as far as i could tell. never really used it but max was talking good about it

**Comment by bumi** [comment]
I've added rollbar. If someone wants an invite, let me know :)
