### ISSUE TITLE
write and add some kind of Terms of Services!

### ISSUE THREAD

**Issue by puneetbharill** [bumi/kuvakehys#18]
As I was asked by Martin, maybe something like this is also required somewhere on the page.

**Comment by bumi** [comment]
what do you mean with privacy? What the pictures are used for? 
At some point we would need some kind of "terms of service"

**Comment by puneetbharill** [comment]
Yes, as Martin was worried that hopefully the pictures are safe and not used for anything. 'terms of services' is the word for it I guess :)
