### ISSUE TITLE
Flow of information on the ordering page

### ISSUE THREAD

**Issue by puneetbharill** [bumi/kuvakehys#21]
I do not like the admin email after the name of the custom album. Is it possible to put it below the address the album is going to?

**Comment by bumi** [comment]
done

**Comment by puneetbharill** [comment]
Is it not deployed yet? I don't see it changed.

**Comment by bumi** [comment]
no not deployed. 
but yes true issues should only be closed once it is deployed. 

...but now it is deployed.

**Comment by puneetbharill** [comment]
:) cool! I just thought in case there was a mistake. Thanks!
