### ISSUE TITLE
Removal of the default group name

### ISSUE THREAD

**Issue by puneetbharill** [bumi/kuvakehys#22]
People do not get it and end up with a long email address they cannot use. I would say something like this-
Name your easy to remember photo album
Edit for the text below it:
All photos sent to this address will now be collected and printed
Share this address with your loved ones so that they can participate too!

**Comment by bumi** [comment]
we have to think about the wording. 

what is a album/ group / package. 
these should be consistent. 

what does the user create? what does he receive in the mail? I think best would be to have names that reference already known meanings. - like for example a photo roll? 

but anyway these great default names are gone :/

**Comment by bumi** [comment]
btw. is it me or is "your loved ones" super cheesy?

**Comment by puneetbharill** [comment]
haha it is kind of cheesy but remember, mothers with babies are gonna use it! We can remove it and put something else. I do not understand what a 'photo roll' means. I try to keep the world album everywhere because that's what it is for now. We can of course change that depending on the product we want to create.

**Comment by bumi** [comment]
aaahhhh. not sure if I want my code to handle all these baby photos. ;) :baby: :baby_bottle: 

but what is the album? the "group" the "order" what comes in the post? 

isn't that a photo roll: https://encrypted.google.com/search?q=%22photo+roll%22&hl=en&tbm=isch&tbo=u&source=univ&sa=X&ved=0CDMQsARqFQoTCJrft5KliMkCFcXsDgodIqwLNg&biw=1406&bih=741

**Comment by puneetbharill** [comment]
So I think the album is both the group and what comes in the post and that is why it is easy association so that people label it as 'silvester2015' or 'bumibirthday' or whatever and remember it easily. I know what a photo roll is but I said I don't understand it because we call it just the reel or negatives and I think different people call it differently.

**Comment by bumi** [comment]
btw. these examples that you give are all event specific and not ongoing (like the original usecase)

**Comment by puneetbharill** [comment]
OK 'Eli_walks' 'MilaReichau', doesn't matter. They were just example.

**Comment by puneetbharill** [comment]
I changed the 'loved ones' thingy...don't know if you get updated if I change my comment. Is that good enough for your code? ;)

**Comment by bumi** [comment]
ok. thanks
