### ISSUE TITLE
send out welcome email after a group is setup

### ISSUE THREAD

**Issue by bumi** [bumi/kuvakehys#23]
after the group is we should send out a welcome email:

* explaining again how tasveer works
* group email address
* what's the best way to use it. (constantly send in photos) 
* URL to manage the group
* content that can be forwarded to friends to let them know how tasveer works and where to send photos (maybe as a second email) 

later we can also split this up in several emails that we send over the first days after a group is created to remind the owner to use it.

**Comment by puneetbharill** [comment]
Just added some text in the wiki. Please take a look and comment.

**Comment by bumi** [comment]
works. pretty nice email!
