### ISSUE TITLE
support different photo formats for printing

### ISSUE THREAD

**Issue by bumi** [bumi/kuvakehys#4]
we should analyze the format of the uploaded images and see if we can match them to proper print sizes. 
for example quadratic pictures should printed quadratic.

**Comment by bumi** [comment]
the printer currently does not support quadratic prints :(  - one requirement for choosing the next one.

**Comment by homtec** [comment]
what happens when printing square formats? are they printed with white border?

**Comment by bumi** [comment]
yes, it tries to fit the picture best without cropping. so we will have a
white border.

I have a test print coming to see how it will look.


On Sunday, October 18, 2015, homtec <notifications@github.com> wrote:

> what happens when printing square formats? are they printed with white
> border?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bumi/kuvakehys/issues/4#issuecomment-149004264>.
>


-- 
Michael Bumann

F       +49 (0) 176 22747893
E       hello@michaelbumann.com
T       twitter.com/bumi

**Comment by bumi** [comment]
yes, it tries to fit the picture best without cropping. so we will have a
white border.

I have a test print coming.

On Sunday, October 18, 2015, homtec <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> what happens when printing square formats? are they printed with white
> border?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bumi/kuvakehys/issues/4#issuecomment-149004264>.
>


-- 
Michael Bumann

F       +49 (0) 176 22747893
E       hello@michaelbumann.com
T       twitter.com/bumi

**Comment by bumi** [comment]
I've changed the config to "Crop" which means that the pictures get cropped if the do not fit. 
This prevents the whitespace but probably destroys square pictures. 
https://github.com/bumi/kuvakehys/commit/6304afe0569956a2fd5911cc3082d1c8dedb5182#commitcomment-13981505

**Comment by bumi** [comment]
cropping is way better. sadly it cuts of some parts. but I think for not we leave it like that.
