### ISSUE TITLE
send inactivity reminders to participants

### ISSUE THREAD

**Issue by bumi** [bumi/kuvakehys#6]
To remind people to send in photos we should notify users after certain inactivity. 
In total we should send 3 notifications: 
1 week after the last photo
3 weeks after the last photo
6 weeks after the last photo

notifications are sent via whatsapp or email

**Comment by bumi** [comment]
done in: 0947c828c928fa1620d2de70a7f279436f2035f8
needs some testing.

**Comment by bumi** [comment]
@puneetbharill text for the inactivity email is here: https://github.com/bumi/kuvakehys/blob/master/app/views/user_mailer/inactivity_notification.text.erb

**Comment by puneetbharill** [comment]
We should probably define inactivity as 'group inactivity' and not 'user inactivity'

**Comment by bumi** [comment]
good point. 

but we also want to incentive more all people to contribute. So if I look at my groups all the photos are sent in from me, which means the group is active but other people currently are inactive. 
Guess that means we should somehow have both. 

send an email if a user is inactive and send an email to all contributors if a group gets inactive.

**Comment by puneetbharill** [comment]
Yes, completely agree.

**Comment by bumi** [comment]
reminders to participants are sent. not for group activity. but if we want that we should create another issue.
