### ISSUE TITLE
should the first package arrive faster?

### ISSUE THREAD

**Issue by bumi** [bumi/kuvakehys#9]
it might be hard to convince people to send in 25+ photos and I guess nothing explains the service better than seeing it. So we could send the first package after maybe 10photos? 
This would give the first time users a faster response/success.

**Comment by puneetbharill** [comment]
Good idea. People are indeed finding it hard to send 25 photos.

**Comment by bumi** [comment]
what would be a good number of photos?

also do you think they find it hard in general or just for the firsr
package?


On Monday, October 19, 2015, puneetbharill <notifications@github.com> wrote:

> Good idea. People are indeed finding it hard to send 25 photos.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bumi/kuvakehys/issues/9#issuecomment-149190864>.
>


-- 
Michael Bumann

F       +49 (0) 176 22747893
E       hello@michaelbumann.com
T       twitter.com/bumi

**Comment by puneetbharill** [comment]
I think 10 is a good number. Also yes, I think it is just the first time thing. I am always explaining that this is a test and the idea would be to just send photos as you take them and it should not be a problem and people seem to get it. So I wouldn't worry about it.
